### PR TITLE
Add more highlights and some fixes

### PR DESCRIPTION
**Pull request by a-pav**
Some [command criteria](https://i3wm.org/docs/userguide.html#command_criteria) like `all|floating|tiling` take no value. To support these, I made the value part of single criterion `for_window` match optional.

**Before:**
for_window_single_criterion_no_value_before_2024-06-21 18-16-02

**After:**
for_window_single_criterion_with_no_value_after2024-06-21 18-17-25

### CODE REVIEW

**Comment by a-pav** [comment]
Highlight `title_format`

title_format_after_2024-06-22 00-27-35

Highlight `title_window_icon`
title_window_icon_after_2024-06-22 00-25-38

**Comment by a-pav** [comment]
Highlight `include`

image

**Comment by a-pav** [comment]
@dcasella Sorry but this PR is no longer just about its title.

After submitting this PR, I just kept discovering more things to make a patch for. Fortunately, now I've just discovered Github's "draft PR" feature! :)) 

Since I'll be probably making even more patches, I've converted this PR to a **draft**. Later I'll mark it as `Ready for review`. Hopefully you'll get a notification then.

Please let me know whether you're OK with this flow, or do you prefer smaller PRs for each patch, as before. And give your feedback and suggestions about the changes.

**Comment by dcasella** [comment]
I'm fine with this, I can even follow commit by commit given how precise you make them.
Thanks!

**Comment by a-pav** [comment]
Highlight bar color classes https://i3wm.org/docs/userguide.html#_colors
<details>
<summary>Before</summary>

bar_colors_before_2024-06-23 13-25-56

</details>

<details>
<summary>After</summary>

bar_colors_after_2024-06-23 13-36-38

</details>

**Comment by a-pav** [comment]
<details>
  <summary>After recent changes:</summary>

after_recent_changes_2024-06-23 19-03-30

</details>

**Comment by a-pav** [comment]
<details>
    <summary>Before:</summary>
    
resize_shrink_before_2024-06-25 14-01-55

</details>

<details>
    <summary>After:</summary>
    
resize_shrink_after_2024-06-25 14-21-28

</details>

**Comment by a-pav** [comment]
<details>
    <summary>Recent changes:</summary>
   

image


mv_cont_to_ws_before2024-06-25 18-36-38


mv_cont_to_ws_after_2024-06-25 18-37-34

</details>

**Comment by dcasella** [comment]
Pretty damn awesome!
I believe the whole i3 VS Code community would thank you for the amazing work done 😀.

**Comment by a-pav** [comment]
Thank you! I was happy to help.

**Pull request merged**
